version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    stdin_open: true
    tty: true
    init: true
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - ./:/app:cached